# Quercus macdougalli

## Denovo+referencia, Q. lobata 

### ipyrad

In [33]:
#Importar librerias
import ipyrad as ip

In [34]:
## Crear un objeto Ensamble llamado data1. 
data2 = ip.Assembly("data2")

New Assembly: data2

In [35]:
## setting/modifying parameters for this Assembly object
data2.set_params('project_dir', "../../results/ipyrad_qlobata_qmacdou/")
data2.set_params('sorted_fastq_path', "../../data/raw/*.fastq.gz")
data2.set_params('assembly_method', "denovo+reference")
data2.set_params('reference_sequence', "../../data/reference_genomes/bwaAll.fasta")
data2.set_params('datatype', 'ddrad')
data2.set_params('filter_adapters', 0)
data2.set_params('max_alleles_consens', 2)
data2.set_params('min_samples_locus', 2)
data2.set_params('trim_reads', (5, 120, 0, 0))

## prints the parameters to the screen
data2.get_params()

0   assembly_name               data2
1   project_dir                 ~/Bioinformatic/Qmacdougallii_genomics_and_environment/results/ipyrad_qlobata_qmacdou
2   raw_fastq_path
3   barcodes_path
4   sorted_fastq_path           ~/Bioinformatic/Qmacdougallii_genomics_and_environment/data/raw/*.fastq.gz
5   assembly_method             denovo+reference
6   reference_sequence          ~/Bioinformatic/Qmacdougallii_genomics_and_environment/data/reference_genomes/bwaAll.fasta
7   datatype                    ddrad
8   restriction_overhang        ('TGCAG', '')
9   max_low_qual_bases          5
10  phred_Qscore_offset         33
11  mindepth_statistical        6
12  mindepth_majrule            6
13  maxdepth                    10000
14  clust_threshold             0.85
15  max_barcode_mismatch        0
16  filter_adapters             0
17  filter_min_trim_len         35
18  max_alleles_consens         2
19  max_Ns_consens              0.05
20  max_Hs_consens              0.05
21  min_samples_locus           2
22  max_SNPs_locus              0.2
23  max_Indels_locus            8
24  max_shared_Hs_locus         0.5
25  trim_reads                  (5, 120, 0, 0)
26  trim_loci                   (0, 0, 0, 0)
27  output_formats              ['p', 's', 'l']
28  pop_assign_file
29  reference_as_filter

Paso 1:

In [36]:
## run step 1 to create Samples objects
data2.run("1", auto=True, force=True)

Parallel connection | jaz-pc: 12 cores
[####################] 100% 0:05:35 | loading reads        | s1 |
Parallel connection closed.

In [37]:
data2.stats

               state  reads_raw
CR_01_S115001      1     811465
CR_02_S127001      1     819482
CR_03_S139001      1     730980
CR_04_S151001      1     815001
CR_05_S163001      1     786398
CR_06_S175001      1     717508
CR_07_S186001      1     768568
CR_08_S104001      1     780528
CR_09_S116001      1     786655
CR_10_S128001      1     747804
CY_01_S170001      1     822962
CY_02_S181001      1     933531
CY_03_S99001       1     720650
CY_04_S111001      1     829645
CY_05_S123001      1     906198
CY_06_S135001      1     852183
CY_07_S147001      1     922627
CY_08_S159001      1     908653
CY_09_S171001      1     678136
CY_10_S182001      1     882121
CZ_01_S100001      1     895135
CZ_02_S112001      1     744109
CZ_03_S124001      1     862573
CZ_04_S136001      1     941946
CZ_05_S148001      1     932356
CZ_06_S160001      1     930248
CZ_07_S172001      1     886574
CZ_08_S183001      1     952933
CZ_09_S101001      1     935423
CZ_10_S113001      1     806309
LS_01_S140001      1     712822
LS_02_S152001      1     799562
LS_03_S164001      1     726253
LS_04_S176001      1     575514
LS_05_S187001      1     702336
MB_01_S95001       1     810310
MB_02_S107001      1     781180
MB_03_S119001      1     825317
MB_04_S131001      1     817207
MB_05_S143001      1     881724
MB_06_S155001      1     907266
MB_07_S167001      1     759179
MB_08_S178001      1     907520
MB_09_S96001       1     800020
MB_10_S108001      1     785136
MC_01_S120001      1     830425
MC_02_S132001      1     799528
MC_03_S144001      1     824890
MC_04_S156001      1     861187
MC_05_S168001      1     720935
MC_06_S179001      1     830285
MC_07_S97001       1     774440
MC_08_S109001      1     820456
MC_09_S121001      1     832398
MC_10_S133001      1     773936
MT_01_S145001      1     874162
MT_02_S157001      1     872099
MT_03_S169001      1     692687
MT_04_S180001      1     804316
MT_05_S98001       1     854761
MT_06_S110001      1     798131
MT_07_S122001      1     893938
MT_08_S134001      1     791590
MT_09_S146001      1     884408
MT_10_S158001      1     879349
PZ_01_S125001      1     837703
PZ_02_S137001      1     864088
PZ_03_S149001      1     845602
PZ_04_S161001      1     474829
PZ_05_S173001      1     700654
PZ_06_S184001      1     466562
PZ_07_S102001      1     892521
PZ_08_S114001      1     852384
PZ_09_S126001      1     898858
PZ_10_S138001      1     758489
PZ_11_S150001      1     855507
PZ_12_S162001      1     847958
PZ_13_S174001      1     761193
PZ_14_S185001      1     827819
PZ_15_S103001      1     787040

Paso 2: Filtrado

In [40]:
## run step 2 to create Samples objects
data2.run("2", auto=True, force=True)

Parallel connection | jaz-pc: 12 cores
[####################] 100% 0:08:58 | processing reads     | s2 |
Parallel connection closed.

In [41]:
data2.stats

               state  reads_raw  reads_passed_filter
CR_01_S115001      2     811465               811457
CR_02_S127001      2     819482               819478
CR_03_S139001      2     730980               730973
CR_04_S151001      2     815001               814996
CR_05_S163001      2     786398               786388
CR_06_S175001      2     717508               717502
CR_07_S186001      2     768568               768563
CR_08_S104001      2     780528               780523
CR_09_S116001      2     786655               786645
CR_10_S128001      2     747804               747794
CY_01_S170001      2     822962               822949
CY_02_S181001      2     933531               933522
CY_03_S99001       2     720650               720636
CY_04_S111001      2     829645               829639
CY_05_S123001      2     906198               906185
CY_06_S135001      2     852183               852178
CY_07_S147001      2     922627               922621
CY_08_S159001      2     908653               908644
CY_09_S171001      2     678136               678128
CY_10_S182001      2     882121               882118
CZ_01_S100001      2     895135               895122
CZ_02_S112001      2     744109               744106
CZ_03_S124001      2     862573               862568
CZ_04_S136001      2     941946               941934
CZ_05_S148001      2     932356               932349
CZ_06_S160001      2     930248               930240
CZ_07_S172001      2     886574               886566
CZ_08_S183001      2     952933               952925
CZ_09_S101001      2     935423               935412
CZ_10_S113001      2     806309               806302
LS_01_S140001      2     712822               712818
LS_02_S152001      2     799562               799557
LS_03_S164001      2     726253               726250
LS_04_S176001      2     575514               575507
LS_05_S187001      2     702336               702326
MB_01_S95001       2     810310               810302
MB_02_S107001      2     781180               781172
MB_03_S119001      2     825317               825309
MB_04_S131001      2     817207               817195
MB_05_S143001      2     881724               881720
MB_06_S155001      2     907266               907258
MB_07_S167001      2     759179               759173
MB_08_S178001      2     907520               907516
MB_09_S96001       2     800020               800015
MB_10_S108001      2     785136               785127
MC_01_S120001      2     830425               830420
MC_02_S132001      2     799528               799525
MC_03_S144001      2     824890               824885
MC_04_S156001      2     861187               861180
MC_05_S168001      2     720935               720931
MC_06_S179001      2     830285               830278
MC_07_S97001       2     774440               774435
MC_08_S109001      2     820456               820452
MC_09_S121001      2     832398               832391
MC_10_S133001      2     773936               773932
MT_01_S145001      2     874162               874149
MT_02_S157001      2     872099               872095
MT_03_S169001      2     692687               692682
MT_04_S180001      2     804316               804308
MT_05_S98001       2     854761               854753
MT_06_S110001      2     798131               798126
MT_07_S122001      2     893938               893929
MT_08_S134001      2     791590               791586
MT_09_S146001      2     884408               884402
MT_10_S158001      2     879349               879345
PZ_01_S125001      2     837703               837695
PZ_02_S137001      2     864088               864084
PZ_03_S149001      2     845602               845595
PZ_04_S161001      2     474829               474824
PZ_05_S173001      2     700654               700646
PZ_06_S184001      2     466562               466558
PZ_07_S102001      2     892521               892512
PZ_08_S114001      2     852384               852374
PZ_09_S126001      2     898858               898852
PZ_10_S138001      2     758489               758482
PZ_11_S150001      2     855507               855496
PZ_12_S162001      2     847958               847953
PZ_13_S174001      2     761193               761190
PZ_14_S185001      2     827819               827809
PZ_15_S103001      2     787040               787032

Paso 3: Agrupamiento y mapeo a genoma de referencia

In [7]:
## run step 3
data2.run("3", auto=True, force=True)

Assembly: data2
[####################] 100%  indexing reference    | 0:15:38 | s3 |
[####################] 100%  dereplicating         | 0:00:35 | s3 |
[####################] 100%  mapping               | 0:40:43 | s3 |
[####################] 100%  clustering            | 0:45:38 | s3 |
[####################] 100%  building clusters     | 0:00:47 | s3 |
[####################] 100%  fetch mapped reads    | 0:03:12 | s3 |
[####################] 100%  chunking              | 0:00:23 | s3 |
[####################] 100%  aligning              | 3:31:57 | s3 |
[####################] 100%  concatenating         | 0:00:52 | s3 |

In [8]:
## run step 4
data2.run("4")

Assembly: data2
[####################] 100%  inferring [H, E]      | 0:02:07 | s4 |

In [16]:
data2.run("5")

Assembly: data2
[####################] 100%  calculating depths    | 0:00:06 | s5 |
[####################] 100%  chunking clusters     | 0:00:06 | s5 |
[####################] 100%  consens calling       | 0:07:26 | s5 |

In [17]:
data2.stats

,state,reads_raw,reads_passed_filter,refseq_mapped_reads,refseq_unmapped_reads,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
QM10_S437001,5,4120245,4119152,2411128,285123,151217,24425,0.048903,0.015510,10289
QM9_S436001,5,5044646,5043189,2830727,681499,211069,16477,0.030829,0.016193,6862

In [18]:
data2.run("6")

Assembly: data2
[####################] 100%  concat/shuffle input  | 0:00:00 | s6 |
[####################] 100%  clustering across     | 0:00:02 | s6 |
[####################] 100%  building clusters     | 0:00:00 | s6 |
[####################] 100%  aligning clusters     | 0:00:01 | s6 |
[####################] 100%  database indels       | 0:00:00 | s6 |
[####################] 100%  indexing clusters     | 0:00:03 | s6 |
[####################] 100%  building database     | 0:00:00 | s6 |

In [19]:
data2.stats

,state,reads_raw,reads_passed_filter,refseq_mapped_reads,refseq_unmapped_reads,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
QM10_S437001,6,4120245,4119152,2411128,285123,151217,24425,0.048903,0.015510,10289
QM9_S436001,6,5044646,5043189,2830727,681499,211069,16477,0.030829,0.016193,6862

In [24]:
data2.run("7", force=True)

Assembly: data2
[####################] 100%  filtering loci        | 0:00:00 | s7 |
[####################] 100%  building loci/stats   | 0:00:00 | s7 |
[####################] 100%  building vcf file     | 0:00:02 | s7 |
[####################] 100%  writing vcf file      | 0:00:00 | s7 |
[####################] 100%  building arrays       | 0:00:00 | s7 |
[####################] 100%  writing outfiles      | 0:00:00 | s7 |
Outfiles written to: ~/Quercus/quercus_macdougallii_qlobata/data2_outfiles

In [25]:
data2.stats

,state,reads_raw,reads_passed_filter,refseq_mapped_reads,refseq_unmapped_reads,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
QM10_S437001,6,4120245,4119152,2411128,285123,151217,24425,0.048903,0.015510,10289
QM9_S436001,6,5044646,5043189,2830727,681499,211069,16477,0.030829,0.016193,6862