# Quercus macdougalli

## Denovo

## ipyrad

In [26]:
#Importar librerias
import ipyrad as ip
#Imprimir versi√≥n
print ip.__version__

0.7.24

In [27]:
## Crear un objeto Ensamble llamado data1. 
denovo_8 = ip.Assembly("denovo_8")

New Assembly: denovo_8

In [28]:
## prints the parameters to the screen
denovo_8.get_params()

0   assembly_name               denovo_8
1   project_dir                 ./
2   raw_fastq_path
3   barcodes_path
4   sorted_fastq_path
5   assembly_method             denovo
6   reference_sequence
7   datatype                    rad
8   restriction_overhang        ('TGCAG', '')
9   max_low_qual_bases          5
10  phred_Qscore_offset         33
11  mindepth_statistical        6
12  mindepth_majrule            6
13  maxdepth                    10000
14  clust_threshold             0.85
15  max_barcode_mismatch        0
16  filter_adapters             0
17  filter_min_trim_len         35
18  max_alleles_consens         2
19  max_Ns_consens              (5, 5)
20  max_Hs_consens              (8, 8)
21  min_samples_locus           4
22  max_SNPs_locus              (20, 20)
23  max_Indels_locus            (8, 8)
24  max_shared_Hs_locus         0.5
25  trim_reads                  (0, 0, 0, 0)
26  trim_loci                   (0, 0, 0, 0)
27  output_formats              ['p', 's', 'v']
28  pop_assign_file

In [29]:
## setting/modifying parameters for this Assembly object
denovo_8.set_params('sorted_fastq_path', "../ref_map_prueba/input/clean/*.fastq")
denovo_8.set_params('min_samples_locus', 2)
denovo_8.set_params('datatype', 'ddrad')
denovo_8.set_params('output_formats', ['p', 's', 'k', 'g', 'v'])

## prints the parameters to the screen
denovo_8.get_params()

0   assembly_name               denovo_8
1   project_dir                 ./
2   raw_fastq_path
3   barcodes_path
4   sorted_fastq_path           /home/alejandro/Escritorio/Quercus/Campos_Project_002/ref_map_prueba/input/clean/*.fastq
5   assembly_method             denovo
6   reference_sequence
7   datatype                    ddrad
8   restriction_overhang        ('TGCAG', '')
9   max_low_qual_bases          5
10  phred_Qscore_offset         33
11  mindepth_statistical        6
12  mindepth_majrule            6
13  maxdepth                    10000
14  clust_threshold             0.85
15  max_barcode_mismatch        0
16  filter_adapters             0
17  filter_min_trim_len         35
18  max_alleles_consens         2
19  max_Ns_consens              (5, 5)
20  max_Hs_consens              (8, 8)
21  min_samples_locus           2
22  max_SNPs_locus              (20, 20)
23  max_Indels_locus            (8, 8)
24  max_shared_Hs_locus         0.5
25  trim_reads                  (0, 0, 0, 0)
26  trim_loci                   (0, 0, 0, 0)
27  output_formats              ('p', 's', 'k', 'g', 'v')
28  pop_assign_file

In [30]:
## run step 1 to create Samples objects
denovo_8.run("1")

Assembly: denovo_8
[####################] 100%  loading reads         | 0:00:58 | s1 |

In [31]:
denovo_8.stats

               state  reads_raw
cleanQM10*001      1    1374649
cleanQM11*001      1    2402121
cleanQM12*001      1    1877577
cleanQM13*001      1     826878
cleanQM14*001      1    1707170
cleanQM15*001      1    3219399
cleanQM16*001      1    2581918
cleanQM9*001       1    1894697

In [32]:
## run step 2 to create Samples objects
denovo_8.run("2")

Assembly: denovo_8
[####################] 100%  processing reads      | 0:06:15 | s2 |

In [33]:
denovo_8.stats

               state  reads_raw  reads_passed_filter
cleanQM10*001      2    1374649              1374645
cleanQM11*001      2    2402121              2402097
cleanQM12*001      2    1877577              1877566
cleanQM13*001      2     826878               826870
cleanQM14*001      2    1707170              1707163
cleanQM15*001      2    3219399              3219369
cleanQM16*001      2    2581918              2581892
cleanQM9*001       2    1894697              1894689

In [34]:
## run step 3
denovo_8.run("3")

Assembly: denovo_8
[####################] 100%  dereplicating         | 0:00:55 | s3 |
[####################] 100%  clustering            | 7:00:25 | s3 |
[####################] 100%  building clusters     | 0:01:29 | s3 |
[####################] 100%  chunking              | 0:00:16 | s3 |
[####################] 100%  aligning              | 4:55:49 | s3 |
[####################] 100%  concatenating         | 0:00:26 | s3 |

In [35]:
denovo_8.stats

,state,reads_raw,reads_passed_filter,clusters_total,clusters_hidepth
cleanQM10*001,3,1374649,1374645,59017,10808
cleanQM11*001,3,2402121,2402097,85015,14951
cleanQM12*001,3,1877577,1877566,89051,13982
cleanQM13*001,3,826878,826870,121731,15733
cleanQM14*001,3,1707170,1707163,107175,18330
cleanQM15*001,3,3219399,3219369,264712,34789
cleanQM16*001,3,2581918,2581892,138099,21611
cleanQM9*001,3,1894697,1894689,140313,16743

In [36]:
## run step 4
denovo_8.run("4")

Assembly: denovo_8
[####################] 100%  inferring [H, E]      | 0:05:15 | s4 |

In [37]:
denovo_8.stats

,state,reads_raw,reads_passed_filter,clusters_total,clusters_hidepth,hetero_est,error_est
cleanQM10*001,4,1374649,1374645,59017,10808,0.053756,0.006288
cleanQM11*001,4,2402121,2402097,85015,14951,0.053707,0.005349
cleanQM12*001,4,1877577,1877566,89051,13982,0.050736,0.005663
cleanQM13*001,4,826878,826870,121731,15733,0.044387,0.006192
cleanQM14*001,4,1707170,1707163,107175,18330,0.051303,0.005660
cleanQM15*001,4,3219399,3219369,264712,34789,0.044924,0.005018
cleanQM16*001,4,2581918,2581892,138099,21611,0.047520,0.004889
cleanQM9*001,4,1894697,1894689,140313,16743,0.049949,0.005965

In [38]:
## run step 5
denovo_8.run("5")

Assembly: denovo_8
[####################] 100%  calculating depths    | 0:00:23 | s5 |
[####################] 100%  chunking clusters     | 0:00:24 | s5 |
[####################] 100%  consens calling       | 0:17:27 | s5 |

In [39]:
denovo_8.stats

,state,reads_raw,reads_passed_filter,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
cleanQM10*001,5,1374649,1374645,59017,10808,0.053756,0.006288,4388
cleanQM11*001,5,2402121,2402097,85015,14951,0.053707,0.005349,5893
cleanQM12*001,5,1877577,1877566,89051,13982,0.050736,0.005663,5294
cleanQM13*001,5,826878,826870,121731,15733,0.044387,0.006192,7639
cleanQM14*001,5,1707170,1707163,107175,18330,0.051303,0.005660,8153
cleanQM15*001,5,3219399,3219369,264712,34789,0.044924,0.005018,15068
cleanQM16*001,5,2581918,2581892,138099,21611,0.047520,0.004889,9441
cleanQM9*001,5,1894697,1894689,140313,16743,0.049949,0.005965,6922

In [40]:
## run step 6
denovo_8.run("6")

Assembly: denovo_8
[####################] 100%  concat/shuffle input  | 0:00:01 | s6 |
[####################] 100%  clustering across     | 0:00:22 | s6 |
[####################] 100%  building clusters     | 0:00:01 | s6 |
[####################] 100%  aligning clusters     | 0:00:47 | s6 |
[####################] 100%  database indels       | 0:00:03 | s6 |
[####################] 100%  indexing clusters     | 0:00:09 | s6 |
[####################] 100%  building database     | 0:00:00 | s6 |

In [41]:
denovo_8.stats

,state,reads_raw,reads_passed_filter,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
cleanQM10*001,6,1374649,1374645,59017,10808,0.053756,0.006288,4388
cleanQM11*001,6,2402121,2402097,85015,14951,0.053707,0.005349,5893
cleanQM12*001,6,1877577,1877566,89051,13982,0.050736,0.005663,5294
cleanQM13*001,6,826878,826870,121731,15733,0.044387,0.006192,7639
cleanQM14*001,6,1707170,1707163,107175,18330,0.051303,0.005660,8153
cleanQM15*001,6,3219399,3219369,264712,34789,0.044924,0.005018,15068
cleanQM16*001,6,2581918,2581892,138099,21611,0.047520,0.004889,9441
cleanQM9*001,6,1894697,1894689,140313,16743,0.049949,0.005965,6922

In [42]:
## run step 7
denovo_8.run("7")

Assembly: denovo_8
[####################] 100%  filtering loci        | 0:00:13 | s7 |
[####################] 100%  building loci/stats   | 0:00:01 | s7 |
[####################] 100%  building vcf file     | 0:00:06 | s7 |
[####################] 100%  writing vcf file      | 0:00:00 | s7 |
[####################] 100%  building arrays       | 0:00:02 | s7 |
[####################] 100%  writing outfiles      | 0:00:01 | s7 |
Outfiles written to: ~/Escritorio/Quercus/Campos_Project_002/ipyrad/denovo_8_outfiles

In [43]:
denovo_8.stats

,state,reads_raw,reads_passed_filter,clusters_total,clusters_hidepth,hetero_est,error_est,reads_consens
cleanQM10*001,6,1374649,1374645,59017,10808,0.053756,0.006288,4388
cleanQM11*001,6,2402121,2402097,85015,14951,0.053707,0.005349,5893
cleanQM12*001,6,1877577,1877566,89051,13982,0.050736,0.005663,5294
cleanQM13*001,6,826878,826870,121731,15733,0.044387,0.006192,7639
cleanQM14*001,6,1707170,1707163,107175,18330,0.051303,0.005660,8153
cleanQM15*001,6,3219399,3219369,264712,34789,0.044924,0.005018,15068
cleanQM16*001,6,2581918,2581892,138099,21611,0.047520,0.004889,9441
cleanQM9*001,6,1894697,1894689,140313,16743,0.049949,0.005965,6922